import type { SeedTaxonomyNode } from "@/domains/enrichment/domain/seedTaxonomy";

/** Verified spend tree from merchant audit (Sep 2026). */
export const VERIFIED_TAXONOMY: SeedTaxonomyNode[] = [
  { facet: "section", name: "Technology" },

  { facet: "category", name: "Employment", parentSlug: "income" },
  { facet: "category", name: "Government & Tax", parentSlug: "income" },
  { facet: "category", name: "Cashback & Rebates", parentSlug: "income" },

  { facet: "category", name: "Utilities & Telecom", parentSlug: "home" },
  { facet: "category", name: "Home Maintenance", parentSlug: "home" },

  { facet: "category", name: "AI Services", parentSlug: "technology" },
  { facet: "category", name: "Software", parentSlug: "technology" },
  { facet: "category", name: "Cloud & Hosting", parentSlug: "technology" },

  { facet: "category", name: "Debt & Loans", parentSlug: "finance" },
  { facet: "category", name: "Banking Fees", parentSlug: "finance" },

  { facet: "category", name: "External Transfers", parentSlug: "transfers" },
  { facet: "category", name: "Cash & ATM", parentSlug: "transfers" },

  { facet: "category", name: "Medical", parentSlug: "health" },

  { facet: "section", name: "Travel" },
  { facet: "section", name: "Family" },
  { facet: "section", name: "Food" },
  { facet: "section", name: "Development" },

  { facet: "category", name: "Lodging", parentSlug: "travel" },
  { facet: "category", name: "Flights", parentSlug: "travel" },
  { facet: "category", name: "Attractions & Tours", parentSlug: "travel" },
  { facet: "category", name: "Childcare", parentSlug: "family" },
  { facet: "category", name: "Kids", parentSlug: "family" },
  { facet: "category", name: "Elder Support", parentSlug: "family" },
  { facet: "category", name: "Pets", parentSlug: "family" },

  { facet: "category", name: "Auto Care & Expenses", parentSlug: "transport" },
  { facet: "category", name: "Rideshare", parentSlug: "transport" },
  { facet: "category", name: "Transit", parentSlug: "transport" },
  { facet: "category", name: "Dealership", parentSlug: "transport" },

  { facet: "category", name: "Groceries", parentSlug: "food" },
  { facet: "category", name: "Restaurants", parentSlug: "food" },
  { facet: "category", name: "Takeout", parentSlug: "food" },
  { facet: "category", name: "Delivery", parentSlug: "food" },
  { facet: "category", name: "Specialty Food", parentSlug: "food" },
  { facet: "category", name: "Drink", parentSlug: "food" },
  { facet: "category", name: "Alcohol", parentSlug: "food" },

  { facet: "category", name: "Shopping", parentSlug: "lifestyle" },
  { facet: "category", name: "Entertainment", parentSlug: "lifestyle" },
  { facet: "category", name: "Insurance", parentSlug: "finance" },
  { facet: "category", name: "Investments", parentSlug: "finance" },
  { facet: "category", name: "Personal Care", parentSlug: "lifestyle" },
  { facet: "category", name: "Education", parentSlug: "development" },
  { facet: "category", name: "Career", parentSlug: "development" },
  { facet: "category", name: "Books", parentSlug: "development" },
  { facet: "category", name: "Fuel", parentSlug: "transport" },
  { facet: "category", name: "Account Transfers", parentSlug: "transfers" },

  { facet: "subcategory", name: "Salary & Wages", parentSlug: "employment" },
  { facet: "subcategory", name: "Tax Refunds", parentSlug: "government-and-tax" },
  { facet: "subcategory", name: "Tax Credits & GST", parentSlug: "government-and-tax" },
  { facet: "subcategory", name: "Cashback Rewards", parentSlug: "cashback-and-rebates" },

  { facet: "subcategory", name: "Mobile & Wireless", parentSlug: "utilities-and-telecom" },
  { facet: "subcategory", name: "Hardware & Tools", parentSlug: "home-maintenance" },

  { facet: "subcategory", name: "Supermarket", parentSlug: "groceries" },
  { facet: "subcategory", name: "Fast Food", parentSlug: "restaurants" },
  { facet: "subcategory", name: "Casual Dining", parentSlug: "restaurants" },
  { facet: "subcategory", name: "Board Game Cafes", parentSlug: "recreational" },
  { facet: "subcategory", name: "Food Delivery", parentSlug: "delivery" },

  { facet: "subcategory", name: "Car Wash", parentSlug: "auto-care-and-expenses" },
  { facet: "subcategory", name: "Maintenance", parentSlug: "auto-care-and-expenses" },
  { facet: "subcategory", name: "Parking", parentSlug: "auto-care-and-expenses" },
  { facet: "subcategory", name: "Rideshare", parentSlug: "rideshare" },
  { facet: "subcategory", name: "Public Transit", parentSlug: "transit" },
  { facet: "subcategory", name: "Service & Sales", parentSlug: "dealership" },

  { facet: "subcategory", name: "Hotels & Vacation Rentals", parentSlug: "lodging" },
  { facet: "subcategory", name: "Airline Tickets", parentSlug: "flights" },
  { facet: "subcategory", name: "Car Rental", parentSlug: "vehicle" },
  { facet: "subcategory", name: "In-Flight", parentSlug: "flights" },
  { facet: "subcategory", name: "Attractions & Tours", parentSlug: "attractions-and-tours" },

  { facet: "subcategory", name: "Clinics & Telehealth", parentSlug: "medical" },
  { facet: "subcategory", name: "Barbers & Salons", parentSlug: "personal-care" },
  { facet: "subcategory", name: "Cosmetics", parentSlug: "personal-care" },
  { facet: "subcategory", name: "Gym Memberships", parentSlug: "personal-care" },
  { facet: "subcategory", name: "Veterinary", parentSlug: "pets" },

  { facet: "subcategory", name: "Video Games & Digital Goods", parentSlug: "entertainment" },
  { facet: "subcategory", name: "Attractions", parentSlug: "entertainment" },
  { facet: "subcategory", name: "Cinemas", parentSlug: "entertainment" },
  { facet: "subcategory", name: "Streaming", parentSlug: "entertainment" },
  { facet: "subcategory", name: "Courses & Training", parentSlug: "education" },
  { facet: "subcategory", name: "Print & Ebooks", parentSlug: "books" },

  { facet: "subcategory", name: "Department & Online Stores", parentSlug: "shopping" },
  { facet: "subcategory", name: "Apparel", parentSlug: "shopping" },
  { facet: "subcategory", name: "Convenience", parentSlug: "shopping" },
  { facet: "subcategory", name: "Hobbies", parentSlug: "shopping" },
  { facet: "subcategory", name: "Pet Supplies", parentSlug: "pets" },

  { facet: "subcategory", name: "AI Assistants & Chat", parentSlug: "ai-services" },
  { facet: "subcategory", name: "AI Code Editors & IDEs", parentSlug: "ai-services" },
  { facet: "subcategory", name: "Model APIs & Inference", parentSlug: "ai-services" },

  { facet: "subcategory", name: "Productivity & Creative", parentSlug: "software-and-subscriptions" },
  { facet: "subcategory", name: "Communication & Social", parentSlug: "software-and-subscriptions" },
  { facet: "subcategory", name: "Security & Utilities", parentSlug: "software-and-subscriptions" },

  { facet: "subcategory", name: "Infrastructure", parentSlug: "cloud-and-hosting" },
  { facet: "subcategory", name: "Domains & Registrars", parentSlug: "cloud-and-hosting" },
  { facet: "subcategory", name: "Developer & Payment Platforms", parentSlug: "cloud-and-hosting" },

  { facet: "subcategory", name: "Student Loans", parentSlug: "debt-and-loans" },
  { facet: "subcategory", name: "Personal Financing", parentSlug: "debt-and-loans" },
  { facet: "subcategory", name: "BNPL", parentSlug: "debt-and-loans" },

  { facet: "subcategory", name: "Monthly Fees", parentSlug: "banking-fees" },
  { facet: "subcategory", name: "Overdraft & Interest", parentSlug: "banking-fees" },
  { facet: "subcategory", name: "Transfer Fees", parentSlug: "banking-fees" },

  { facet: "subcategory", name: "Property & Auto Insurance", parentSlug: "insurance" },
  { facet: "subcategory", name: "Payment Protection", parentSlug: "insurance" },
  { facet: "subcategory", name: "Brokerage & Crypto", parentSlug: "investments" },

  { facet: "subcategory", name: "Credit Card Payoffs", parentSlug: "account-transfers" },
  { facet: "subcategory", name: "Self Transfers", parentSlug: "account-transfers" },
  { facet: "subcategory", name: "Interac e-Transfer", parentSlug: "external-transfers" },
  { facet: "subcategory", name: "Remittances", parentSlug: "external-transfers" },
  { facet: "subcategory", name: "ATM Withdrawals", parentSlug: "cash-and-atm" },
  { facet: "subcategory", name: "Cash Advances", parentSlug: "cash-and-atm" },
];

/** Legacy category/subcategory → verified tree. */
export const LEGACY_CATEGORY_MERGES: Array<{
  from: string;
  to: string;
  section: string;
}> = [
  { from: "Employment Income", to: "Employment", section: "Income" },
  { from: "Salary and Wages", to: "Employment", section: "Income" },
  { from: "Tax Benefits and Credits", to: "Government & Tax", section: "Income" },
  { from: "Tax Refunds", to: "Government & Tax", section: "Income" },
  { from: "Rewards", to: "Cashback & Rebates", section: "Income" },
  { from: "Rewards and Cashback", to: "Cashback & Rebates", section: "Income" },
  { from: "Rewards and Rebates", to: "Cashback & Rebates", section: "Income" },
  { from: "Utilities", to: "Utilities & Telecom", section: "Home" },
  { from: "Home Improvement", to: "Home Maintenance", section: "Home" },
  { from: "Rent and Housing", to: "Housing", section: "Home" },
  { from: "Software & Subscriptions", to: "Software", section: "Technology" },
  { from: "Software and Subscriptions", to: "Software", section: "Technology" },
  { from: "Loans", to: "Debt & Loans", section: "Finance" },
  { from: "Loan Payments", to: "Debt & Loans", section: "Finance" },
  { from: "Bank Fees", to: "Banking Fees", section: "Finance" },
  { from: "Medical Care", to: "Medical", section: "Health" },
  { from: "Auto", to: "Auto Care & Expenses", section: "Transport" },
  { from: "Automotive", to: "Auto Care & Expenses", section: "Transport" },
  { from: "Auto Dealers and Services", to: "Dealership", section: "Transport" },
  { from: "Transit & Flights", to: "Flights", section: "Travel" },
  { from: "Airlines", to: "Flights", section: "Travel" },
  { from: "Travel", to: "Flights", section: "Travel" },
  { from: "General Shopping", to: "Shopping", section: "Lifestyle" },
  { from: "Rideshare & Transit", to: "Rideshare", section: "Transport" },
  { from: "Rideshare and Transit", to: "Rideshare", section: "Transport" },
  { from: "Money Transfers", to: "External Transfers", section: "Transfers" },
  { from: "Remittance", to: "External Transfers", section: "Transfers" },
  { from: "Bank Transfers", to: "Account Transfers", section: "Transfers" },
  { from: "Food and Drink", to: "Groceries", section: "Food" },
  { from: "Food", to: "Groceries", section: "Food" },
  { from: "Delivery Services", to: "Delivery", section: "Food" },
  { from: "Restaurants & Cafes", to: "Restaurants", section: "Food" },
  { from: "Government Services", to: "Home Maintenance", section: "Home" },
  { from: "Cash", to: "Cash & ATM", section: "Transfers" },
  { from: "ATM", to: "Cash & ATM", section: "Transfers" },
  { from: "Cash and ATM", to: "Cash & ATM", section: "Transfers" },
];

export const LEGACY_SUBCATEGORY_MERGES: Array<{
  from: string;
  to: string;
  parentSlug: string;
}> = [
  { from: "Paycheck", to: "Salary & Wages", parentSlug: "employment" },
  { from: "Payroll", to: "Salary & Wages", parentSlug: "employment" },
  { from: "Tax Credits", to: "Tax Credits & GST", parentSlug: "government-and-tax" },
  { from: "GST/HST Credit", to: "Tax Credits & GST", parentSlug: "government-and-tax" },
  { from: "Tax Refund", to: "Tax Refunds", parentSlug: "government-and-tax" },
  { from: "Cashback", to: "Cashback Rewards", parentSlug: "cashback-and-rebates" },
  { from: "Mobile Phone", to: "Mobile & Wireless", parentSlug: "utilities-and-telecom" },
  { from: "Hardware Stores", to: "Hardware & Tools", parentSlug: "home-maintenance" },
  { from: "Registry Services", to: "Hardware & Tools", parentSlug: "home-maintenance" },
  { from: "Groceries", to: "Supermarket", parentSlug: "groceries" },
  { from: "Supermarkets", to: "Supermarket", parentSlug: "groceries" },
  { from: "Dine-In", to: "Casual Dining", parentSlug: "restaurants" },
  { from: "Delivery", to: "Food Delivery", parentSlug: "delivery" },
  { from: "Gas Stations", to: "Gas Stations", parentSlug: "fuel" },
  { from: "Rideshare", to: "Rideshare", parentSlug: "rideshare" },
  { from: "Public Transit", to: "Public Transit", parentSlug: "transit" },
  { from: "Car Dealerships", to: "Service & Sales", parentSlug: "dealership" },
  { from: "Auto Repair and Maintenance", to: "Maintenance", parentSlug: "auto-care-and-expenses" },
  { from: "Lodging", to: "Hotels & Vacation Rentals", parentSlug: "lodging" },
  { from: "Online Travel Agency", to: "Hotels & Vacation Rentals", parentSlug: "lodging" },
  { from: "Flights", to: "Airline Tickets", parentSlug: "flights" },
  { from: "Airline Tickets", to: "Airline Tickets", parentSlug: "flights" },
  { from: "In-flight Services", to: "In-Flight", parentSlug: "flights" },
  { from: "Car Rental", to: "Car Rental", parentSlug: "vehicle" },
  { from: "Entertainment Venues", to: "Attractions", parentSlug: "entertainment" },
  { from: "Sports", to: "Attractions & Tours", parentSlug: "attractions-and-tours" },
  { from: "Movie Theaters", to: "Cinemas", parentSlug: "entertainment" },
  { from: "Movie Theatres", to: "Cinemas", parentSlug: "entertainment" },
  { from: "Video Games", to: "Video Games & Digital Goods", parentSlug: "entertainment" },
  { from: "Games and Hobbies", to: "Hobbies", parentSlug: "shopping" },
  { from: "Streaming Services", to: "Streaming", parentSlug: "entertainment" },
  { from: "Online Marketplaces", to: "Department & Online Stores", parentSlug: "shopping" },
  { from: "Department Stores", to: "Department & Online Stores", parentSlug: "shopping" },
  { from: "Clothing and Apparel", to: "Apparel", parentSlug: "shopping" },
  { from: "Convenience Store", to: "Convenience", parentSlug: "shopping" },
  { from: "Craft and Hobby Stores", to: "Hobbies", parentSlug: "shopping" },
  { from: "Barbers", to: "Barbers & Salons", parentSlug: "personal-care" },
  { from: "Hair Salons", to: "Barbers & Salons", parentSlug: "personal-care" },
  { from: "Hair Salons and Barbers", to: "Barbers & Salons", parentSlug: "personal-care" },
  { from: "Gyms", to: "Gym Memberships", parentSlug: "personal-care" },
  { from: "Retail", to: "Cosmetics", parentSlug: "personal-care" },
  { from: "Pet Stores", to: "Pet Supplies", parentSlug: "pets" },
  { from: "Medical Services", to: "Clinics & Telehealth", parentSlug: "medical" },
  { from: "Pharmacies", to: "Clinics & Telehealth", parentSlug: "medical" },
  { from: "SaaS", to: "Productivity & Creative", parentSlug: "software-and-subscriptions" },
  { from: "Cloud Software", to: "Infrastructure", parentSlug: "cloud-and-hosting" },
  { from: "Developer Tools", to: "Infrastructure", parentSlug: "cloud-and-hosting" },
  { from: "Buy Now Pay Later", to: "BNPL", parentSlug: "debt-and-loans" },
  { from: "Loan Payment", to: "Personal Financing", parentSlug: "debt-and-loans" },
  { from: "Student Loans", to: "Student Loans", parentSlug: "debt-and-loans" },
  { from: "Service Charges", to: "Monthly Fees", parentSlug: "banking-fees" },
  { from: "Account Fee", to: "Monthly Fees", parentSlug: "banking-fees" },
  { from: "Interest", to: "Overdraft & Interest", parentSlug: "banking-fees" },
  { from: "Interest Charges", to: "Overdraft & Interest", parentSlug: "banking-fees" },
  { from: "Transfer Fee", to: "Transfer Fees", parentSlug: "banking-fees" },
  { from: "Service Fee", to: "Monthly Fees", parentSlug: "banking-fees" },
  { from: "Payment Protection", to: "Payment Protection", parentSlug: "insurance" },
  { from: "Auto & Property", to: "Property & Auto Insurance", parentSlug: "insurance" },
  { from: "Investment Deposit", to: "Brokerage & Crypto", parentSlug: "investments" },
  { from: "Credit Card Payment", to: "Credit Card Payoffs", parentSlug: "account-transfers" },
  { from: "Internal Transfers", to: "Self Transfers", parentSlug: "account-transfers" },
  { from: "Internal Transfer", to: "Self Transfers", parentSlug: "account-transfers" },
  { from: "P2P Transfers", to: "Interac e-Transfer", parentSlug: "external-transfers" },
  { from: "E-Transfer", to: "Interac e-Transfer", parentSlug: "external-transfers" },
  { from: "International Remittance", to: "Remittances", parentSlug: "external-transfers" },
  { from: "International Transfers", to: "Remittances", parentSlug: "external-transfers" },
  { from: "Wire Transfer", to: "Remittances", parentSlug: "external-transfers" },
  { from: "Investment Transfer", to: "Self Transfers", parentSlug: "account-transfers" },
  { from: "ATM Withdrawal", to: "ATM Withdrawals", parentSlug: "cash-and-atm" },
  { from: "ATM Withdrawals", to: "ATM Withdrawals", parentSlug: "cash-and-atm" },
  { from: "Cash Advance", to: "Cash Advances", parentSlug: "cash-and-atm" },
  { from: "Cash Advances", to: "Cash Advances", parentSlug: "cash-and-atm" },
];
