/** Starter section/category/subcategory paths for statement labeling. */
export const SEED_CATEGORY_PATHS: Array<{
  section: string;
  category: string;
  subcategory: string | null;
}> = [
  { section: "Lifestyle", category: "Food", subcategory: null },
  { section: "Lifestyle", category: "Food", subcategory: "Restaurants" },
  { section: "Lifestyle", category: "Food", subcategory: "Delivery" },
  { section: "Lifestyle", category: "Food", subcategory: "Groceries" },
  { section: "Lifestyle", category: "Drink", subcategory: null },
  { section: "Lifestyle", category: "Drink", subcategory: "Coffee" },
  { section: "Lifestyle", category: "Entertainment", subcategory: null },
  { section: "Lifestyle", category: "Entertainment", subcategory: "Video Games" },
  { section: "Lifestyle", category: "Entertainment", subcategory: "Entertainment Venues" },
  { section: "Lifestyle", category: "Entertainment", subcategory: "Sports" },
  { section: "Lifestyle", category: "Entertainment", subcategory: "Movie Theatres" },
  { section: "Lifestyle", category: "Shopping", subcategory: null },
  { section: "Lifestyle", category: "Shopping", subcategory: "Online Marketplaces" },
  { section: "Lifestyle", category: "Software", subcategory: null },
  { section: "Lifestyle", category: "Software", subcategory: "Cloud Software" },
  { section: "Lifestyle", category: "Software", subcategory: "SaaS" },
  { section: "Lifestyle", category: "Software", subcategory: "Developer Tools" },
  { section: "Lifestyle", category: "Subscriptions", subcategory: null },
  { section: "Lifestyle", category: "Subscriptions", subcategory: "Streaming Services" },
  { section: "Lifestyle", category: "Personal Care", subcategory: null },
  { section: "Lifestyle", category: "Personal Care", subcategory: "Gyms" },
  { section: "Lifestyle", category: "Personal Care", subcategory: "Hair Salons" },
  { section: "Lifestyle", category: "Personal Care", subcategory: "Barbers" },
  { section: "Home", category: "Utilities", subcategory: null },
  { section: "Home", category: "Rent", subcategory: null },
  { section: "Home", category: "Housing", subcategory: null },
  { section: "Transport", category: "Fuel", subcategory: null },
  { section: "Transport", category: "Fuel", subcategory: "Gas Stations" },
  { section: "Transport", category: "Rideshare", subcategory: null },
  { section: "Transport", category: "Transit", subcategory: null },
  { section: "Transport", category: "Travel", subcategory: null },
  { section: "Transport", category: "Auto", subcategory: null },
  { section: "Transport", category: "Auto", subcategory: "Auto Repair and Maintenance" },
  { section: "Transport", category: "Auto", subcategory: "Car Dealerships" },
  { section: "Transport", category: "Auto", subcategory: "Car Wash" },
  { section: "Finance", category: "Bank Fees", subcategory: null },
  { section: "Finance", category: "Insurance", subcategory: null },
  { section: "Finance", category: "Insurance", subcategory: "Payment Protection" },
  { section: "Finance", category: "Loans", subcategory: null },
  { section: "Finance", category: "Loans", subcategory: "Loan Payment" },
  { section: "Finance", category: "Loans", subcategory: "Student Loans" },
  { section: "Finance", category: "Loans", subcategory: "Buy Now Pay Later" },
  { section: "Finance", category: "Investments", subcategory: null },
  { section: "Health", category: "Medical", subcategory: null },
  { section: "Health", category: "Medical", subcategory: "Pharmacies" },
  { section: "Health", category: "Medical", subcategory: "Medical Services" },
  { section: "Income", category: "Employment Income", subcategory: null },
  { section: "Income", category: "Employment Income", subcategory: "Paycheck" },
  { section: "Income", category: "Government Benefits", subcategory: null },
  { section: "Income", category: "Government Benefits", subcategory: "Tax Credits" },
  { section: "Income", category: "Rewards", subcategory: null },
  { section: "Income", category: "Rewards", subcategory: "Cashback" },
  { section: "Transfers", category: "Money Transfers", subcategory: null },
  { section: "Transfers", category: "Money Transfers", subcategory: "E-Transfer" },
  { section: "Transfers", category: "Money Transfers", subcategory: "International Remittance" },
  { section: "Transfers", category: "Account Transfers", subcategory: null },
  { section: "Transfers", category: "Account Transfers", subcategory: "Credit Card Payment" },
  { section: "Transfers", category: "Account Transfers", subcategory: "Internal Transfers" },
  { section: "Transfers", category: "Cash & ATM", subcategory: null },
];
