/**
 * Short blurbs for spend-tree lookup rows (sections, categories, …).
 * Unknown names fall back to a generic line so inserts always have text.
 */

function norm(value: string) {
  return value.trim().toLowerCase();
}

const SECTIONS: Record<string, string> = {
  finance: "Banking, debt, insurance, and investments.",
  lifestyle: "Shopping, entertainment, personal care, and hobbies.",
  food: "Groceries, restaurants, takeout, delivery, and drinks.",
  transfers: "Money moved between accounts or people (not household spend).",
  income: "Pay, benefits, cashback, and other real money in.",
  technology: "Software, AI tools, and cloud.",
  transport: "Daily getting around: fuel, transit, rideshare, and the car.",
  health: "Medical, dental, vision, and therapy.",
  home: "Housing costs, utilities, furnishings, and home maintenance.",
  travel: "Trips away from home: flights, lodging, and attractions.",
  family: "Childcare, kids, pets, and elder support.",
  development: "Courses, career costs, books, and other learning.",
};

const CATEGORIES: Record<string, string> = {
  "ai services": "AI apps, assistants, editors, and model APIs.",
  alcohol: "Beer, wine, and liquor bought to take home.",
  "account transfers": "Moves between your own accounts or card payoffs.",
  "attractions & tours": "Tickets, tours, and paid sightseeing.",
  attractions: "Tickets, tours, and paid sightseeing.",
  "auto care & expenses": "Car wash, maintenance, parking, tolls, and upkeep.",
  auto: "Car wash, maintenance, parking, tolls, and upkeep.",
  "banking fees": "Monthly fees, overdraft, interest, ATM, FX, and transfer fees.",
  "business services": "Accounting, legal, and advertising for side work.",
  career: "Licences, exams, and professional events.",
  books: "Print books, ebooks, and audiobooks.",
  "cash & atm": "ATM withdrawals and cash advances.",
  atm: "ATM withdrawals and cash advances.",
  "cashback & rebates": "Card rewards and merchant rebates credited to you.",
  cashback: "Card rewards and merchant rebates credited to you.",
  "cloud & hosting": "Infrastructure, domains, and developer platforms.",
  cloud: "Infrastructure, domains, and developer platforms.",
  dealership: "Dealer service, parts, and vehicle sales.",
  "debt & loans": "Loan payments, BNPL, credit interest, and personal financing.",
  loans: "Loan payments, BNPL, credit interest, and personal financing.",
  delivery: "Food delivery apps and delivery fees.",
  "delivery services": "Food delivery apps and delivery fees.",
  dental: "Cleanings, fillings, and other dental care.",
  devices: "Computers, phones, and tech accessories.",
  drink: "Coffee, tea, and cafe drinks (not alcohol).",
  education: "Courses, classes, tuition, and training.",
  childcare: "Daycare, babysitting, and after-school care.",
  kids: "Kids clothing, toys, and activities.",
  "elder support": "Money or care costs for a parent or dependent.",
  fitness: "Classes, gear, and coaching. Gym dues stay under Personal Care.",
  furnishings: "Furniture, appliances, and decor.",
  "gifts & giving": "Personal gifts and charity.",
  gifts: "Personal gifts and charity.",
  employment: "Salary, wages, and employer pay.",
  entertainment: "Streaming, games, cinema, bars, and paid leisure.",
  "external transfers": "e-Transfer, remittance, and money to other people.",
  flights: "Airline tickets and in-flight purchases.",
  food: "Use Groceries, Restaurants, Takeout, or Delivery instead.",
  groceries: "Supermarket, produce, convenience, and meal kits.",
  restaurants: "Eating out: fast food, casual, fine dining, and cafes.",
  takeout: "Restaurant pickup and prepared meals.",
  "specialty food": "Bakery, butcher, and specialty grocery.",
  fuel: "Gas stations and vehicle fuel.",
  "government & tax": "Tax refunds, tax credits, and GST/HST credits.",
  tax: "Tax refunds, tax credits, and GST/HST credits.",
  "government benefits": "Unemployment, child benefit, pension, and social assistance.",
  "home maintenance": "Repairs, hardware, tool rental, and home upkeep.",
  housing: "Rent and mortgage payments.",
  insurance: "Property, auto, life, tenant, health, and travel coverage.",
  investments: "Brokerage, crypto, retirement accounts, and trading fees.",
  lodging: "Hotels and vacation rentals.",
  medical: "Clinics, hospital, pharmacies, and supplements.",
  "mobile & wireless": "Phone plans and mobile service.",
  "personal care": "Hair, gym, cosmetics, and toiletries.",
  pets: "Pet food, supplies, vet, grooming, and boarding.",
  recreational: "Paid recreation: golf, pickleball, ranges, and game cafes.",
  "tax payments": "Income tax and property tax you pay.",
  therapy: "Counselling and psychotherapy.",
  "vehicle payments": "Car loan and lease payments.",
  vision: "Eye exams, glasses, and contacts.",
  rentals: "Short-term car hire.",
  rideshare: "Uber, Lyft, and similar rides.",
  shopping: "Stores, apparel, electronics, and online retail.",
  sightseeing: "Museums, cultural sites, and sightseeing.",
  software: "Apps, SaaS, and digital tools.",
  "software & subscriptions": "Apps, SaaS, and digital tools.",
  streaming: "Video and music streaming services.",
  transit: "Public transit and passes.",
  "utilities & telecom": "Power, water, internet, and telecom bills.",
  utilities: "Power, water, internet, and telecom bills.",
  vehicle: "Car rental and vehicle hire.",
};

const SUBCATEGORIES: Record<string, string> = {
  "ai assistants & chat": "ChatGPT-style assistants and chat products.",
  assistants: "ChatGPT-style assistants and chat products.",
  "ai code editors & ides": "AI coding editors and IDE add-ons.",
  "code editors": "AI coding editors and IDE add-ons.",
  "atm withdrawals": "Cash taken from an ATM.",
  "airline tickets": "Booked flights and airfare.",
  apparel: "Clothing and accessories.",
  "attractions & tours": "Paid attractions and guided tours.",
  "barbers & salons": "Haircuts and salon services.",
  barbers: "Haircuts.",
  salons: "Salon services.",
  "board game cafes": "Cafe visits centered on games.",
  "brokerage & crypto": "Brokerage trades and crypto moves.",
  brokerage: "Brokerage trades and deposits.",
  crypto: "Crypto trades and deposits.",
  "car insurance": "Vehicle insurance premiums.",
  "car rental": "Short-term car hire.",
  "car wash": "Car wash and detailing.",
  "cash advances": "Cash advances on a card or LOC.",
  "cashback rewards": "Cashback credited from cards or merchants.",
  "cellphone plan": "Mobile phone plan charges.",
  cinemas: "Movie tickets and theater snacks.",
  "clinics & telehealth": "Doctor visits and telehealth.",
  clinics: "Doctor visits and telehealth.",
  coffee: "Coffee shops and cafe drinks.",
  "communication & social": "Messaging and social apps.",
  communication: "Messaging and social apps.",
  "convenience stores": "Convenience and corner stores.",
  "courses & training": "Courses, classes, and training.",
  courses: "Courses, classes, and training.",
  cosmetics: "Makeup and beauty products.",
  "credit card payoffs": "Paying down your own credit card.",
  "department & online stores": "Department stores and big online retailers.",
  "online stores": "Department stores and big online retailers.",
  "developer & payment platforms": "Dev platforms and payment processors.",
  developer: "Developer platforms.",
  payments: "Payment processors.",
  "dine-in": "Eating out at restaurants.",
  "discount stores": "Discount and dollar stores.",
  "domains & registrars": "Domain names and DNS registrars.",
  domains: "Domain names and DNS registrars.",
  "driving range": "Golf driving range fees.",
  "education & training": "Courses, classes, and training.",
  electricity: "Electric and power bills.",
  electronics: "Gadgets and electronics.",
  "equipment rental": "Short-term equipment or tool rentals.",
  "fast food": "Quick-service and fast food.",
  "food delivery": "Meal delivery apps and couriers.",
  fuel: "Fuel purchased at the pump.",
  "gas stations": "Gas station purchases.",
  golf: "Golf fees and related spend.",
  "gym memberships": "Gym and fitness memberships.",
  "hardware & tools": "Hardware stores and tools.",
  hardware: "Hardware stores and tools.",
  hobbies: "Hobby supplies and kits.",
  hotels: "Hotel stays.",
  "hotels & vacation rentals": "Hotels and short-term stays.",
  "in-flight": "Purchases made on a flight.",
  infrastructure: "Cloud servers and hosting infra.",
  "interac e-transfer": "Interac e-Transfer to/from a person.",
  maintenance: "Vehicle repairs and maintenance.",
  "mobile & wireless": "Mobile/wireless plan charges.",
  mobile: "Mobile/wireless plan charges.",
  "model apis & inference": "Paid AI model API usage.",
  "model apis": "Paid AI model API usage.",
  "monthly fees": "Recurring bank account fees.",
  mortgage: "Home mortgage payments.",
  "museums & culture": "Museums, galleries, and cultural venues.",
  museums: "Museums, galleries, and cultural venues.",
  "overdraft & interest": "Overdraft fees and interest charges.",
  interest: "Overdraft fees and interest charges.",
  overdraft: "Overdraft fees.",
  parking: "Parking lots and meters.",
  "payment protection": "Payment protection insurance.",
  "personal financing": "Personal loans and financing.",
  "pet supplies": "Pet food and supplies.",
  pharmacies: "Pharmacy purchases.",
  pickleball: "Pickleball courts and gear.",
  prescriptions: "Prescription medication.",
  "productivity & creative": "Productivity and creative software.",
  productivity: "Productivity software.",
  creative: "Creative software.",
  "property & auto insurance": "Home and auto insurance.",
  "home insurance": "Home insurance premiums.",
  "public transit": "Bus, train, and transit fares.",
  recreation: "General recreation spend.",
  remittances: "International remittances and money sent abroad.",
  rent: "Rent paid to a landlord.",
  "rent payment": "Rent paid to a landlord.",
  restaurants: "Restaurant meals.",
  supermarket: "Grocery supermarket trips.",
  produce: "Fruit, vegetables, and produce shops.",
  "convenience store": "Corner-store food and snacks.",
  "meal kits": "Prepared grocery kits and meal boxes.",
  "casual dining": "Sit-down restaurants that are not fine dining.",
  "fine dining": "Upscale restaurant meals.",
  cafes: "Cafe meals. Coffee-only stays under Drink.",
  "restaurant pickup": "Meals picked up from a restaurant.",
  "prepared meals": "Ready-to-eat meals that are not delivery.",
  bakery: "Bakeries and baked goods.",
  butcher: "Butcher shops and meat counters.",
  "specialty grocery": "Specialty or ethnic grocery stores.",
  "uber & lyft": "Uber, Lyft, and other app rides.",
  uber: "Uber, Lyft, and other app rides.",
  taxi: "Taxi and cab fares.",
  "salary & wages": "Paycheque and wage deposits.",
  salary: "Paycheque and wage deposits.",
  "security & system tools": "Antivirus, password managers, and system utilities.",
  security: "Antivirus, password managers, and system utilities.",
  "self transfers": "Transfers between your own accounts.",
  "service & sales": "Dealer service and vehicle sales.",
  service: "Dealer service and vehicle sales.",
  sports: "Sports events and gear.",
  streaming: "Streaming subscriptions.",
  "student loans": "Student loan payments.",
  supermarkets: "Grocery supermarket trips.",
  supplements: "Vitamins and supplements.",
  "tax credits & gst": "GST/HST credits and tax benefits.",
  "tax credits": "GST/HST credits and tax benefits.",
  "tax refunds": "Income tax refunds.",
  "theme parks": "Theme park tickets.",
  tickets: "Attraction, event, and tour tickets.",
  tours: "Guided tours.",
  unemployment: "Unemployment or job-insurance benefits.",
  "transfer fees": "Fees charged to move money.",
  veterinary: "Vet visits and pet medical care.",
  "video games & digital goods": "Games and digital content.",
  games: "Games and digital content.",
  accounting: "Bookkeeping, accountant, and tax prep.",
  advertising: "Ads, printing, and branding.",
  appliances: "Home appliances.",
  "atm fees": "Fees charged to use an ATM.",
  "baggage & seat fees": "Checked bags and seat selection.",
  baggage: "Checked bags and seat selection.",
  "bars & pubs": "Bar, pub, and nightclub tabs.",
  bars: "Bar, pub, and nightclub tabs.",
  "bike & scooter": "Bike, scooter, or similar short-term hire.",
  scooter: "Bike, scooter, or similar short-term hire.",
  boarding: "Kennel, pet daycare, or pet sitter.",
  books: "Print, ebook, or audiobook purchases.",
  "print & ebooks": "Print books and ebooks.",
  ebooks: "Print books and ebooks.",
  audiobooks: "Audiobook apps and credits.",
  "car payment": "Vehicle loan payment (not dealer service).",
  certification: "Exams, licences, and professional certs.",
  "child benefit": "Canada child benefit and similar.",
  childcare: "Daycare, babysitting, and after-school care.",
  "checkup & cleaning": "Dental exam and cleaning.",
  checkup: "Dental exam and cleaning.",
  cleaning: "House cleaning and maid service.",
  coaching: "Personal trainer or sports coach.",
  "concerts & events": "Concerts, festivals, theatre, and comedy.",
  concerts: "Concerts, festivals, theatre, and comedy.",
  conferences: "Conferences, meetups, and professional events.",
  computers: "Desktops, laptops, and monitors.",
  "counselling": "Counselling and psychotherapy sessions.",
  "credit card interest": "Interest charged on a credit card.",
  decor: "Home decor and housewares.",
  "delivery fees": "Courier or app delivery fees, not the meal.",
  diesel: "Diesel fuel.",
  "elder support": "Money or care costs for a parent or dependent.",
  "ev charging": "Electric vehicle charging.",
  "eye exam": "Optometrist visits.",
  footwear: "Shoes, boots, and sneakers.",
  "foreign exchange": "FX and currency-conversion fees.",
  furniture: "Home furniture.",
  "glasses & contacts": "Glasses and contact lenses.",
  glasses: "Glasses.",
  contacts: "Contact lenses.",
  grooming: "Pet grooming and nail trims.",
  "health insurance": "Supplemental health or dental insurance.",
  hospital: "Hospital and emergency-room bills.",
  internet: "Home internet service.",
  "investment transfers": "Moves into or out of an investment account.",
  "kids": "Kids clothing, toys, and activities.",
  "lawn & snow": "Lawn care and snow removal.",
  lawn: "Lawn care.",
  snow: "Snow removal.",
  lease: "Vehicle lease payment.",
  legal: "Lawyer, filings, and contract review.",
  licensing: "Professional licence and renewal.",
  "life insurance": "Term or permanent life premiums.",
  "line of credit": "LOC or HELOC payments.",
  "liquor store": "Beer, wine, and liquor retail.",
  "natural gas": "Home natural gas bills.",
  "parking rent": "Rented parking spot at home.",
  pension: "Pension deposits.",
  "personal gifts": "Birthday, wedding, holiday, and similar gifts.",
  "pest control": "Pest control visits.",
  "pet food": "Pet food and treats.",
  phones: "Phones, cases, and chargers.",
  "property tax": "Municipal property tax you pay.",
  registration: "Vehicle registration, licence, and inspection.",
  repairs: "Home repairs (not auto).",
  "retirement accounts": "RRSP, TFSA, 401k, IRA, and pension contributions.",
  "storage rent": "Storage-unit rent.",
  takeout: "Pickup and prepared food, not delivery apps.",
  tea: "Tea shops and packaged tea.",
  "tenant insurance": "Renter insurance.",
  tires: "Tires and tire service.",
  toiletries: "Soap, shampoo, toothpaste, and similar.",
  tolls: "Road, bridge, and congestion charges.",
  "trading fees": "Commissions and investment account fees.",
  "transit pass": "Monthly or weekly transit passes.",
  treatment: "Fillings, ortho, and other dental work.",
  tuition: "University, college, trade, or private-school tuition.",
  tutoring: "Tutors and test prep.",
  "vacation rentals": "Airbnb and similar short-term stays.",
  water: "Water and sewer bills.",
  garbage: "Garbage and recycling pickup.",
  charity: "Nonprofit and community donations.",
  classes: "Yoga, martial arts, and fitness classes.",
  accessories: "Keyboards, mice, headphones, and similar.",
  "income tax": "Income tax you pay (not a refund).",
  "travel insurance": "Medical travel or trip protection.",
  "cash deposits": "Cash put back into an account.",
  daycare: "Daycare and after-school care.",
  babysitting: "Babysitting.",
  "toys & activities": "Kids toys and activities.",
  toys: "Kids toys and activities.",
  "care & support": "Care costs for a parent or dependent.",
  care: "Care costs for a parent or dependent.",
  clothing: "Kids clothing.",
  bonus: "Bonus or incentive pay.",
  "contractor pay": "Freelance or contractor income.",
  disability: "Disability benefit deposits.",
  "social assistance": "Social assistance and income support.",
  "merchant rebates": "Store or brand rebate credits.",
  "p2p apps": "PayPal, Wise, and similar person-to-person apps.",
  housewares: "Kitchenware, linens for the home, and household goods.",
  bedding: "Sheets, pillows, and mattresses.",
  "juice & smoothies": "Juice bars and smoothie shops.",
  juice: "Juice bars.",
  smoothies: "Smoothie shops.",
  "soft drinks": "Soda, bottled drinks, and fountain drinks.",
  "beer & wine store": "Beer and wine shops (not a bar tab).",
  "beer store": "Beer shops (not a bar tab).",
  "wine store": "Wine shops (not a bar tab).",
  seafood: "Fish market and seafood counters.",
  "cheese & deli": "Cheese shops and deli counters.",
  cheese: "Cheese shops.",
  deli: "Deli counters.",
  bowling: "Bowling lanes and related fees.",
  climbing: "Climbing gyms and related fees.",
  "cards & wrapping": "Greeting cards and gift wrap.",
  cards: "Greeting cards and gift wrap.",
  consulting: "Consulting and professional advice.",
  memberships: "Professional association dues.",
  "exam fees": "Professional or licensing exam fees.",
  magazines: "Magazines, journals, and periodicals.",
  tablets: "Tablets and e-readers.",
  wearables: "Watches, earbuds, and wearables.",
  "after school": "After-school care programs.",
  camps: "Day camps and overnight kids camps.",
  "school supplies": "Kids school supplies and backpacks.",
  "home help": "In-home help for a parent or dependent.",
  "guided tours": "Paid guided tours.",
  hostels: "Hostel and budget-dorm stays.",
  "intercity rail": "VIA, Amtrak, and similar intercity rail.",
  parts: "Dealer or aftermarket vehicle parts.",
  orthodontics: "Braces, aligners, and ortho visits.",
  psychiatry: "Psychiatrist visits and related care.",
  "robo-advisor": "Managed investing and robo-advisor fees.",
};

const TYPES: Record<string, string> = {
  expenses: "Money spent on goods and services.",
  income: "Money received as income.",
  transfers: "Money moved, not spent or earned as income.",
};

const KINDS: Record<string, string> = {
  fee: "A fee or service charge.",
  "fee; subscription": "A fee that is also a subscription.",
  interest: "Interest charged or earned.",
  statement: "A statement-related line.",
  subscription: "A recurring subscription charge.",
};

export type TaxonomyFacet =
  | "section"
  | "category"
  | "subcategory"
  | "type"
  | "kind";

const BY_FACET: Record<TaxonomyFacet, Record<string, string>> = {
  section: SECTIONS,
  category: CATEGORIES,
  subcategory: SUBCATEGORIES,
  type: TYPES,
  kind: KINDS,
};

const FALLBACK_LABEL: Record<TaxonomyFacet, string> = {
  section: "Spend section",
  category: "Spend category",
  subcategory: "Spend subcategory",
  type: "Transaction type",
  kind: "Transaction kind",
};

/** Resolve a description for a taxonomy name; never returns empty. */
export function taxonomyDescription(
  facet: TaxonomyFacet,
  name: string,
): string {
  const trimmed = name.trim();
  const known = BY_FACET[facet][norm(trimmed)];
  if (known) return known;
  return `${FALLBACK_LABEL[facet]}: ${trimmed || "Custom"}.`;
}
