/** One-line "what you use this for" notes. Not type docs. */

export const TABLE_HELP: Record<string, string> = {
  institutions: "A bank or card issuer. Statement accounts hang off this.",
  accounts: "A real account at that bank. Checking, credit card, etc.",
  statement_uploads:
    "One PDF statement you uploaded. Totals live here, not on each line.",
  transactions:
    "One flat ledger row matching the transactions CSV. Money, dates, categories on the same row.",
  transaction_sections:
    "Filter lookup for Section (Lifestyle, Transport, Travel, …).",
  transaction_spreads:
    "Filter lookup for 50/30/20 Spread (Needs / Wants / Savings).",
  transaction_categories:
    "Filter lookup for Category (Fuel, Flights, Shopping, …).",
  transaction_subcategories: "Filter lookup for Subcategory.",
  transaction_types:
    "Filter lookup for cash-flow Transaction type (income / transfers / expenses).",
  transaction_kinds:
    "Retired lookup for Type chips. Folded into txn_code (fee / subscription / …).",
  app_modules: "Which app pages show in the sidebar.",
  scratch_notes: "Scratch pads on Analysis (tabs + vendor rows).",
  piggy_pings: "Reminders Piggy or you schedule (toast, email, popup, banner).",
  budgets: "Spend caps Piggy or you set (amount, warn %, over %).",
  users: "Signed-in people. Role controls which modules they get.",
  auth_sessions: "Active login sessions for a user.",
  auth_accounts: "Password / OAuth provider link for a user.",
  auth_refresh_tokens: "Tokens used to renew a session.",
  auth_verification_codes:
    "One-time codes for email verify / magic link / OTP.",
  auth_verifiers: "PKCE verifiers for OAuth handshakes.",
  auth_rate_limits: "Sign-in attempt counters (stops brute force).",
};

export const COLUMN_HELP: Record<string, Record<string, string>> = {
  institutions: {
    id: "This bank's number.",
    institution_id: "Stable key for the bank. Accounts and spends point here.",
    name: "Bank name you see in the UI.",
    created_at: "When this bank was first saved.",
    updated_at: "When we last changed this bank row.",
  },
  accounts: {
    id: "This account's number.",
    account_id: "Stable key for the account. Ledger rows point here.",
    institution_id: "Which bank this account belongs to.",
    name: "Nickname on the dashboard.",
    official_name: "The bank's longer product name.",
    mask: "Last four digits. Match statements and CSV files with this.",
    type: "Broad kind: depository, credit, loan.",
    subtype: "Finer kind: checking, credit card.",
    current_balance: "What the bank says you owe or hold right now.",
    available_balance: "What you can still spend (cards/checking).",
    iso_currency_code: "Currency for the balances (USD, CAD).",
    updated_at: "When we last refreshed this account.",
  },
  statement_uploads: {
    id: "This upload's number. Ledger rows can point back here.",
    filename: "The PDF filename you picked.",
    file_hash: "Fingerprint so we skip the same PDF twice.",
    status: "Where import sits: pending, done, or failed.",
    account_id: "Resolved ledger account when we know which one this PDF is.",
    institution_name: "Bank printed on the statement.",
    account_name: "Account title printed on the statement.",
    account_mask: "Last four digits from the PDF. Match to an account.",
    currency: "Statement currency, usually CAD.",
    page_count: "How many PDF pages we read.",
    transaction_count: "How many lines the parser found.",
    inserted_count: "New ledger rows this import added.",
    updated_count: "Existing ledger rows this import changed.",
    skipped_count: "Lines we did not write (dupes or junk).",
    statement_period_start: "First day this PDF covers.",
    statement_period_end: "Last day this PDF covers.",
    opening_balance: "Balance at the start of the period, from the PDF.",
    closing_balance: "Balance at the end, from the PDF.",
    total_debits: "Money out, as the statement summary listed.",
    total_credits: "Money in, as the statement summary listed.",
    transaction_sum: "All line amounts added up.",
    computed_closing: "Opening plus lines. Should match closing.",
    balance_delta: "Gap between computed close and printed close. Want ~0.",
    balance_ok:
      "1 = PDF math checks out. 0 = mismatch. Empty = we could not tell.",
    ocr_markdown: "Raw text we pulled off the PDF. Debug parse errors here.",
    error: "Why import failed, if it did.",
    created_at: "When you uploaded the PDF.",
    completed_at: "When import finished.",
  },
  transactions: {
    id: "This ledger row's number. Atoms and enrichment point here.",
    transaction_id: "Stable key for this line. Statement imports reuse it.",
    account_id: "Which account this spend hit.",
    description: "Bank memo or merchant text on the line.",
    pending: "Still settling. Skip for 'real spent' until this is off.",
    source: "Where the row came from, usually statement.",
    statement_upload_id: "Which PDF created or updated this row.",
    updated_at: "When we last changed this ledger row.",
    currency: "Ledger currency for the posted amount (usually CAD).",
    foreign_currency: "Original purchase currency when the line is FX.",
    foreign_amount: "Original foreign charge size printed on the statement.",
    exchange_rate: "FX rate printed on the line when present.",
    spread: "50/30/20 bucket name: Needs, Wants, or Savings.",
    spread_id: "FK to transaction_spreads for type-safe Spread filters.",
  },
  transaction_amounts: {
    transaction_id: "Which ledger row this money belongs to.",
    amount_minor: "Amount in cents. Positive = money out. Negative = money in.",
    currency_code: "Currency for this amount (CAD, USD).",
    running_balance_minor:
      "Account balance after this line in cents, if known.",
  },
  transaction_dates: {
    transaction_id: "Which ledger row these dates belong to.",
    posted_date: "Posted date. Use this for 'when it hit the account'.",
    authorized_date: "Day you swiped. Can differ from posted date.",
  },
  transaction_locations: {
    transaction_id: "Which ledger row this place belongs to.",
    city: "City of the swipe, if known.",
    region: "State or province of the swipe.",
    country: "Country of the swipe.",
    postal_code: "Postal code of the swipe.",
  },
  transaction_payment_refs: {
    transaction_id: "Which ledger row these payment refs belong to.",
    check_number: "Check number, if it was a check.",
    reference_number: "Bank reference number on the line.",
    transaction_code: "Line nature: purchase, payment, fee, subscription, …",
    payment_channel: "In store, online, or other.",
    foreign_amount_minor: "Foreign charge size in cents, if present.",
    foreign_currency: "Foreign currency code, if present.",
  },
  transaction_bank_categories: {
    transaction_id:
      "Which ledger row these bank labels belong to (retired table).",
  },
  entities: {
    id: "This merchant node's number.",
    slug: "Stable key (starbucks). Safe to join on.",
    display_name: "Name you read (Starbucks).",
    kind: "company, subsidiary, brand, or product.",
    parent_entity_id: "Parent in the merchant family tree.",
    website: "Merchant site, for logos and lookup.",
    logo_url: "Picture for the merchant in the UI.",
    source: "Who wrote it: seed, ai, or user.",
    created_at: "When we first saved this merchant.",
    updated_at: "When the name or tree last changed.",
  },
  entity_aliases: {
    id: "This alias row's number.",
    entity_id: "Which merchant entity this spelling points to.",
    alias: "Alternate name or memo fragment for the merchant.",
    source: "Who wrote it: seed, ai, or user.",
    created_at: "When we first saved this alias.",
  },
  taxonomy_nodes: {
    id: "This category node's number.",
    facet:
      "Which list: section, category, subcategory, type, transaction_type, tag, store_type, food_type.",
    slug: "Stable key (food).",
    name: "Label you read (Food, Drink).",
    parent_id: "Parent in the spend tree. Empty on top sections.",
    path: "Full trail, for sorting and breadcrumbs.",
    depth: "How far down the tree. 0 is a top section.",
    source: "Who wrote it: seed, ai, or user.",
    created_at: "When we first saved this node.",
    updated_at: "When the tree last changed.",
  },
  transaction_enrichment: {
    id: "This cleanup row's number.",
    transaction_id: "Which ledger row this describes. One per spend.",
    merchant_raw: "Text we started from (bank memo).",
    merchant_clean: "Readable store name after cleanup.",
    channel: "online, in_store, or other.",
    txn_kind: "Line nature: purchase, refund, fee, subscription, payment…",
    store_number: "Chain store number we parsed out.",
    legal_suffix: "Inc, Ltd, etc. stripped off the name.",
    enrichment_status: "pending, done, or failed.",
    enrichment_confidence: "How sure the model was.",
    enrichment_model: "Which AI model wrote this.",
    enriched_at: "When cleanup finished.",
    error: "Why cleanup failed, if it did.",
    updated_at: "When this cleanup row last changed.",
  },
  transaction_entities: {
    id: "This entity link row's number.",
    transaction_id: "Which spend got the entity link.",
    entity_id: "Which merchant entity was linked.",
    role: "company, brand, subsidiary, or product.",
    confidence: "How sure we were about this link.",
    source: "Who applied it: ai, rules, seed, user.",
    created_at: "When the link was added.",
  },
  enrichment_tokens: {
    id: "This token row's number.",
    transaction_id: "Which spend the token came from.",
    token: "One word or fragment parsed from the memo.",
    sort_order: "Order in the original memo split.",
  },
  transaction_labels: {
    id: "This tag row's number.",
    transaction_id: "Which spend got the tag.",
    node_id: "Which taxonomy node was applied.",
    role: "Why it is stuck on: section, category, subcategory, type, tag, store_type, etc.",
    confidence: "How sure we were about this tag.",
    source: "Who applied it: ai, rules, seed, user.",
    created_at: "When the tag was added.",
  },
  bank_history_files: {
    id: "This CSV file's number.",
    filename: "Export filename you imported.",
    file_hash: "Fingerprint so we skip the same CSV twice.",
    account_id: "Ledger account tied to this export, when known.",
    account_mask: "Last four digits on the export.",
    account_type: "Visa, chequing, etc. from the CSV.",
    product_name: "Product title from the export, if present.",
    row_count: "How many history lines we stored.",
    imported_at: "When you imported this CSV.",
  },
  bank_history_rows: {
    id: "This CSV line's number.",
    file_id: "Which export file it came from.",
    fingerprint: "Dedupe key. Same line twice will collide here.",
    account_mask: "Last four digits for this line.",
    account_type: "Account kind on the line.",
    date: "Date the bank put on the CSV.",
    description: "Bank memo from the CSV.",
    debit: "Money out, as the bank wrote it. Empty if it was a credit.",
    credit: "Money in, as the bank wrote it. Empty if it was a debit.",
    direction: "debit or credit. Use this to check PDF sign.",
    amount: "Size of the line (positive).",
    card_number: "Card digits on the line, if present.",
    matched_transaction_id: "Ledger row we paired this CSV line with.",
    match_status: "matched or unmatched against the ledger.",
    bank_direction: "debit or credit after match, when applied to ledger.",
    created_at: "When we stored this CSV line.",
  },
  app_modules: {
    id: "This module's number.",
    slug: "URL key (overview, accounts).",
    name: "Label in the sidebar.",
    description: "One-line pitch on the modules page.",
    href: "Where the sidebar link goes.",
    icon: "Icon name for the nav.",
    category: "core, finance, or system.",
    enabled: "Off hides it from the nav.",
    sort_order: "Lower number sits higher in the list.",
    is_core: "Core modules cannot be turned off.",
    created_at: "When this module row was created.",
    updated_at: "When we last changed it.",
  },
  scratch_notes: {
    tabs: "Note pads (name + vendor spend rows).",
    activeId: "Which tab is open in the UI.",
    receiveId: "Tab that receives dropped vendors.",
    userId: "Who owns this scratch pad.",
    updatedAt: "Last edit time.",
  },
  budgets: {
    name: "Short label for this spend cap.",
    classLookup: "Section, category, or subcategory name to match later.",
    descriptionLookup: "Merchant or description fragment to match later.",
    amount: "Cap in the user's currency.",
    warningThreshold: "Percent of amount that should warn.",
    overageThreshold: "Percent of amount that counts as over.",
    isActive: "Off pauses the budget without deleting it.",
    userId: "Who this budget belongs to.",
    createdAt: "When the budget was created.",
    updatedAt: "When we last changed it.",
  },
  piggy_pings: {
    name: "Short label for this reminder.",
    title: "Headline on the ping.",
    message: "Body of the reminder.",
    pingType: "Primary type. Kept for older rows.",
    pingTypes: "Toast, Email, Popup, and Banner. One ping can use several.",
    cycle: "When it repeats from the start date.",
    trigger: "Reserved for later. Leave empty.",
    triggerCount: "How many times it has fired.",
    isActive: "Off pauses the ping without deleting it.",
    startDate: "First day. Empty = no start bound.",
    endDate: "Last day. Empty = no end bound.",
    notes: "Private notes about this ping.",
    userId: "Who this ping belongs to.",
    createdAt: "When the ping was created.",
    updatedAt: "When we last changed it.",
  },
  users: {
    email: "Login email.",
    name: "Display name.",
    role: "admin, premium, or normal.",
    image: "Avatar URL if set.",
    emailVerificationTime: "When email was verified.",
    phone: "Phone if used for auth.",
    isAnonymous: "True for guest-style accounts.",
  },
  auth_sessions: {
    userId: "Which user this session belongs to.",
    expirationTime: "When the session dies.",
  },
  auth_accounts: {
    userId: "Which user this provider link belongs to.",
    provider: "password, google, etc.",
    providerAccountId: "Provider's id for this account.",
    secret: "Password hash (redacted in browse).",
  },
  auth_refresh_tokens: {
    sessionId: "Session this token renews.",
    expirationTime: "When the refresh token dies.",
    parentRefreshTokenId: "Token that minted this one.",
  },
  auth_verification_codes: {
    accountId: "Auth account waiting for verify.",
    provider: "Which flow issued the code.",
    code: "One-time code (redacted in browse).",
    expirationTime: "When the code stops working.",
  },
  auth_verifiers: {
    sessionId: "Session tied to this PKCE verifier.",
    signature: "Verifier value (redacted in browse).",
  },
  auth_rate_limits: {
    identifier: "Email or key being rate-limited.",
    lastAttemptTime: "Last try timestamp.",
    attemptsLeft: "Tries remaining before lockout.",
  },
  transaction_spreads: {
    id: "This Spread label's number.",
    name: "Spread label: Needs, Wants, or Savings.",
    target_percent: "Target share of net pay: 50, 30, or 20.",
    description: "What this bucket covers in plain language.",
    sort_order: "Display order in filters and charts.",
  },
};

export function tableHelp(table: string) {
  return TABLE_HELP[table];
}

export function columnHelp(table: string, column: string) {
  return COLUMN_HELP[table]?.[column];
}
