/** One-line "what you use this for" notes. Not type docs. */

export const TABLE_HELP: Record<string, string> = {
  plaid_items:
    "A linked bank login. One row per Plaid connection.",
  accounts:
    "A real account at that bank. Checking, credit card, etc.",
  statement_uploads:
    "One PDF statement you uploaded. Totals live here, not on each line.",
  transactions:
    "The ledger. Every spend or credit, from Plaid or a statement.",
  entities:
    "Who you paid: company, brand, or product. Used to group merchants.",
  taxonomy_nodes:
    "The spend tree: section → category → type, plus tags.",
  transaction_enrichment:
    "Our cleaned read of one ledger row. Use this for reports, not the raw bank text.",
  transaction_labels:
    "Extra tags on a ledger row. Many labels can stick to one spend.",
  bank_history_files:
    "One CIBC CSV export. Bank's own debit/credit list.",
  bank_history_rows:
    "One CSV line. Gold standard for 'money in vs money out'.",
  app_modules:
    "Which app pages show in the sidebar.",
};

export const COLUMN_HELP: Record<string, Record<string, string>> = {
  plaid_items: {
    id: "This connection's number.",
    item_id: "Plaid's id for this bank login. Accounts and spends point here.",
    access_token: "Secret we send Plaid to pull this bank again. Do not share.",
    institution_id: "Plaid's code for the bank (CIBC, etc.).",
    institution_name: "Bank name you see in the UI.",
    cursor: "Bookmark so the next sync only fetches new spends.",
    days_requested: "How far back we asked Plaid to go, in days.",
    created_at: "When this bank was first linked.",
    updated_at: "When we last synced or changed this link.",
  },
  accounts: {
    id: "This account's number.",
    plaid_account_id: "Plaid's id for the account. Ledger rows point here.",
    item_id: "Which bank login this account belongs to.",
    name: "Nickname on the dashboard.",
    official_name: "The bank's longer product name.",
    mask: "Last four digits. Match statements and CSV files with this.",
    type: "Broad kind: depository, credit, loan.",
    subtype: "Finer kind: checking, credit card.",
    current_balance: "What the bank says you owe or hold right now.",
    available_balance: "What you can still spend (cards/checking).",
    iso_currency_code: "Currency for the balances (USD, CAD).",
    updated_at: "When we last refreshed this account.",
  },
  statement_uploads: {
    id: "This upload's number. Ledger rows can point back here.",
    filename: "The PDF filename you picked.",
    file_hash: "Fingerprint so we skip the same PDF twice.",
    status: "Where import sits: pending, done, or failed.",
    institution_name: "Bank printed on the statement.",
    account_name: "Account title printed on the statement.",
    account_mask: "Last four digits from the PDF. Match to an account.",
    currency: "Statement currency, usually CAD.",
    page_count: "How many PDF pages we read.",
    transaction_count: "How many lines the parser found.",
    inserted_count: "New ledger rows this import added.",
    updated_count: "Existing ledger rows this import changed.",
    skipped_count: "Lines we did not write (dupes or junk).",
    statement_period_start: "First day this PDF covers.",
    statement_period_end: "Last day this PDF covers.",
    opening_balance: "Balance at the start of the period, from the PDF.",
    closing_balance: "Balance at the end, from the PDF.",
    total_debits: "Money out, as the statement summary listed.",
    total_credits: "Money in, as the statement summary listed.",
    transaction_sum: "All line amounts added up.",
    computed_closing: "Opening plus lines. Should match closing.",
    balance_delta: "Gap between computed close and printed close. Want ~0.",
    balance_ok: "1 = PDF math checks out. 0 = mismatch. Empty = we could not tell.",
    ocr_markdown: "Raw text we pulled off the PDF. Debug parse errors here.",
    error: "Why import failed, if it did.",
    created_at: "When you uploaded the PDF.",
    completed_at: "When import finished.",
  },
  transactions: {
    id: "This ledger row's number. Enrichment and labels point here.",
    plaid_transaction_id: "Plaid's id, or a made-up id for statement lines.",
    account_id: "Which account this spend hit (Plaid account id).",
    item_id: "Which bank login it came from.",
    name: "What you show in the list. Bank memo or merchant.",
    merchant_name: "Store name Plaid or the PDF gave us.",
    merchant_entity_id: "Plaid's merchant id, if they know the store.",
    merchant_category_code: "Card network store type (MCC). Coarse.",
    original_description: "Ugly bank text before cleanup.",
    amount: "How much. Positive = money out. Negative = money in.",
    iso_currency_code: "Currency for this amount.",
    date: "Posted date. Use this for 'when it hit the account'.",
    datetime: "Posted time, if the bank sent one.",
    authorized_date: "Day you swiped. Can differ from posted date.",
    authorized_datetime: "Swipe time, if present.",
    pending: "Still settling. Skip for 'real spent' until this is off.",
    pending_transaction_id: "If this posted row replaced a pending one, that id.",
    category_primary: "Plaid's big bucket (FOOD_AND_DRINK).",
    category_detailed: "Plaid's finer bucket. Ours may override later.",
    category_confidence: "How sure Plaid was about that bucket.",
    payment_channel: "In store, online, or other.",
    transaction_code: "Bank code: purchase, payment, fee, and so on.",
    check_number: "Check number, if it was a check.",
    account_owner: "Whose name is on the account, if Plaid sent it.",
    website: "Merchant site, for logos and lookup.",
    logo_url: "Picture for the merchant in the UI.",
    category_icon_url: "Plaid's icon for their category.",
    location_city: "City of the swipe, if known.",
    location_region: "State or province of the swipe.",
    location_postal_code: "Postal code of the swipe.",
    location_country: "Country of the swipe.",
    location_lat: "Map pin latitude.",
    location_lon: "Map pin longitude.",
    location_address: "Street of the store.",
    location_store_number: "Chain store number (#1234).",
    counterparties_json: "Raw Plaid 'who else was in this payment' blob.",
    payment_meta_json: "Raw Plaid payment extras. Rarely used in UI.",
    running_balance: "Account balance after this line, if the bank sent it.",
    source: "Where the row came from: plaid or statement.",
    statement_upload_id: "Which PDF created or updated this row.",
    bank_direction: "debit or credit after CSV cross-check. Trust this for sign.",
    history_match: "matched = found in CSV. unmatched = PDF-only in that window.",
    updated_at: "When we last changed this ledger row.",
  },
  entities: {
    id: "This merchant node's number.",
    slug: "Stable key (starbucks). Safe to join on.",
    display_name: "Name you read (Starbucks).",
    kind: "company, subsidiary, brand, or product.",
    parent_entity_id: "Parent in the merchant family tree.",
    aliases_json: "Other spellings that mean this same merchant.",
    source: "Who wrote it: seed, ai, or user.",
    created_at: "When we first saved this merchant.",
    updated_at: "When the name or tree last changed.",
  },
  taxonomy_nodes: {
    id: "This category node's number.",
    facet: "Which list: section, category, type, tag, store_type, food_type.",
    slug: "Stable key (food-and-drink).",
    name: "Label you read (Food and Drink).",
    parent_id: "Parent in the spend tree. Empty on top sections.",
    path: "Full trail, for sorting and breadcrumbs.",
    depth: "How far down the tree. 0 is a top section.",
    source: "Who wrote it: seed, ai, or user.",
    created_at: "When we first saved this node.",
    updated_at: "When the tree last changed.",
  },
  transaction_enrichment: {
    id: "This cleanup row's number.",
    transaction_id: "Which ledger row this describes. One per spend.",
    merchant_raw: "Text we started from (bank memo).",
    merchant_clean: "Readable store name after cleanup.",
    company_entity_id: "Parent company (Alimentation Couche-Tard).",
    brand_entity_id: "Brand on the receipt (Circle K).",
    subsidiary_entity_id: "Legal entity under the company, if we split it.",
    product_entity_id: "Specific product, if the line is that narrow.",
    store_type_node_id: "Kind of store (grocery, gas).",
    food_type_node_id: "Kind of food, when it is a meal.",
    section_node_id: "Top spend bucket (Lifestyle, Home).",
    category_node_id: "Mid bucket (Food and Drink).",
    type_node_id: "Fine bucket (Coffee shop).",
    channel: "online, in_store, or other.",
    txn_kind: "What happened: purchase, refund, fee, payment…",
    amount_signed: "Spend as negative, income as positive. For charts.",
    amount_abs: "Size with no sign. For matching and totals.",
    direction: "outflow or inflow after we flipped the bank amount.",
    date_posted: "Posted date, copied for analytics.",
    date_authorized: "Swipe date, copied for analytics.",
    location_city: "City we kept after cleanup.",
    location_region: "State/province we kept.",
    location_country: "Country we kept.",
    store_number: "Chain store number we parsed out.",
    legal_suffix: "Inc, Ltd, etc. stripped off the name.",
    parse_tokens_json: "Words we split the memo into. Debug the cleaner here.",
    enrichment_status: "pending, done, or failed.",
    enrichment_confidence: "How sure the model was.",
    enrichment_model: "Which AI model wrote this.",
    enriched_at: "When cleanup finished.",
    error: "Why cleanup failed, if it did.",
    updated_at: "When this cleanup row last changed.",
  },
  transaction_labels: {
    id: "This tag row's number.",
    transaction_id: "Which spend got the tag.",
    node_id: "Which taxonomy node was applied.",
    role: "Why it is stuck on: section, tag, store_type, etc.",
    confidence: "How sure we were about this tag.",
    source: "Who applied it: ai, rules, seed, user.",
    created_at: "When the tag was added.",
  },
  bank_history_files: {
    id: "This CSV file's number.",
    filename: "Export filename you imported.",
    file_hash: "Fingerprint so we skip the same CSV twice.",
    account_mask: "Last four digits on the export.",
    account_type: "Visa, chequing, etc. from the CSV.",
    product_name: "Product title from the export, if present.",
    row_count: "How many history lines we stored.",
    imported_at: "When you imported this CSV.",
  },
  bank_history_rows: {
    id: "This CSV line's number.",
    file_id: "Which export file it came from.",
    fingerprint: "Dedupe key. Same line twice will collide here.",
    account_mask: "Last four digits for this line.",
    account_type: "Account kind on the line.",
    date: "Date the bank put on the CSV.",
    description: "Bank memo from the CSV.",
    debit: "Money out, as the bank wrote it. Empty if it was a credit.",
    credit: "Money in, as the bank wrote it. Empty if it was a debit.",
    direction: "debit or credit. Use this to check PDF sign.",
    amount: "Size of the line (positive).",
    card_number: "Card digits on the line, if present.",
    source_filename: "Which file this line was read from.",
    matched_transaction_id: "Ledger row we paired this CSV line with.",
    match_status: "matched or unmatched against the ledger.",
    created_at: "When we stored this CSV line.",
  },
  app_modules: {
    id: "This module's number.",
    slug: "URL key (overview, accounts).",
    name: "Label in the sidebar.",
    description: "One-line pitch on the modules page.",
    href: "Where the sidebar link goes.",
    icon: "Icon name for the nav.",
    category: "core, finance, or system.",
    enabled: "Off hides it from the nav.",
    sort_order: "Lower number sits higher in the list.",
    is_core: "Core modules cannot be turned off.",
    created_at: "When this module row was created.",
    updated_at: "When we last changed it.",
  },
};

export function tableHelp(table: string) {
  return TABLE_HELP[table];
}

export function columnHelp(table: string, column: string) {
  return COLUMN_HELP[table]?.[column];
}
